# Generated by Django 5.2.6 on 2025-09-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("QuantifyRegistration", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="job_role",
            field=models.CharField(
                choices=[
                    ("SDE", "Software Development Engineer (7 LPA)"),
                    ("DA", "Data Analyst (7 LPA)"),
                    ("WD", "Web Developer (7 LPA)"),
                    ("QA", "Quality Assurance Engineer (7 LPA)"),
                    ("DS", "Data Scientist (7 LPA)"),
                    ("DBA", "Database Administrator (7 LPA)"),
                    ("HR", "HR Executive (4 LPA)"),
                    ("SE", "Support Engineer (4 LPA)"),
                    ("IT", "IT Administrator (4 LPA)"),
                    ("BA", "Business Analyst (4 LPA)"),
                    ("TS", "Technical Support (4 LPA)"),
                ],
                max_length=50,
            ),
        ),
    ]
